CSS corrections and make a bookDetail view responsive
wolox-training/LL-React pull request #10
Opened 2023-02-03 18:52 UTC by lauuta185

## Summary
In this PR, i make a CSS corrections, and make a bookDetail view responsive.

## Screenshot
<img width="1011" alt="Screenshot 2023-02-03 at 15 45 21" src="https://user-images.githubusercontent.com/108479534/216683610-a12ea002-1679-4bc3-9a05-6a3eba0638b7.png">

## Trello Card
[https://trello.com/c/zlAe650t/34-responsive](url)

2023-02-03 19:58 UTC, MMarussi requested changes

2023-02-03 19:58 UTC, MMarussi commented on Maquetado/scss/bookDetail.scss
> +@media only screen and (max-width: 1024px) {
You can define the breakpoint value in a variable, so in case the the breakpoint changes you only have to change it once

2023-02-03 19:58 UTC, MMarussi commented on Maquetado/scss/bookDetail.scss
> +      justify-content: center;
Is this necessary?

2023-02-03 19:58 UTC, MMarussi commented on Maquetado/views/index.html
>      </div>
Sorry because this is not a change from this PR, but I'm almost sure that this can be simplified in a simple <a> with a pseudo element in css

2023-02-03 19:58 UTC, MMarussi commented on Maquetado/scss/bookDetail.scss
> +      left: 33.5%;
I'm not saying that this achieves the expected result, but generally when we use a percentage value like xx.x% it means that there's something in our elements width / positioning that can be improved

2023-02-03 19:58 UTC, MMarussi commented on Maquetado/scss/bookDetail.scss
> +  padding-bottom: 28%;
Have you tried to replacing this with a `height:100vh`? padding should be used to separate a container from it's content

2023-02-06 15:50 UTC, andres-acc submitted a review, later dismissed

2023-02-06 15:50 UTC, andres-acc commented on Maquetado/scss/bookDetail.scss
> +        margin-right: unset;
```suggestion
        margin: 25px unset 20px unset;
```

2023-02-06 17:36 UTC, MMarussi approved these changes

2023-02-06 17:39 UTC, merged